AllCops:
  TargetRubyVersion: 3.1.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - '**/*.rb'
